import { Task, TaskStatus, TaskPriority } from "@/types";

export const mockData: Task[] = [
  {
    id: 1,
    title: "Write project proposal",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 2,
    title: "Fix login page bug",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.None,
  },
  {
    id: 3,
    title: "Design homepage layout",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 4,
    title: "Update API documentation",
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
  },
  {
    id: 5,
    title: "Refactor user authentication",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 6,
    title: "Optimize database queries",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Low,
  },
  {
    id: 7,
    title: "Review PR #345",
    status: TaskStatus.Completed,
    priority: TaskPriority.Urgent,
  },
  {
    id: 8,
    title: "Implement dark mode",
    status: TaskStatus.Completed,
    priority: TaskPriority.Urgent,
  },
  {
    id: 9,
    title: "Schedule team meeting",
    status: TaskStatus.Completed,
    priority: TaskPriority.Low,
  },
  {
    id: 10,
    title: "Prepare monthly report",
    status: TaskStatus.InProgress,
    priority: TaskPriority.None,
  },
  {
    id: 11,
    title: "Fix CSS styling issue",
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
  },
  {
    id: 12,
    title: "Set up CI/CD pipeline",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Medium,
  },
  {
    id: 13,
    title: "Test new feature deployment",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 14,
    title: "Debug performance issues",
    status: TaskStatus.Completed,
    priority: TaskPriority.None,
  },
  {
    id: 15,
    title: "Create marketing email template",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Urgent,
  },
  {
    id: 16,
    title: "Write unit tests for authentication",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Medium,
  },
  {
    id: 17,
    title: "Optimize frontend rendering",
    status: TaskStatus.Completed,
    priority: TaskPriority.Low,
  },
  {
    id: 18,
    title: "Update dependency versions",
    status: TaskStatus.Completed,
    priority: TaskPriority.Urgent,
  },
  {
    id: 19,
    title: "Research competitor products",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 20,
    title: "Draft feature roadmap",
    status: TaskStatus.Completed,
    priority: TaskPriority.High,
  },
  {
    id: 21,
    title: "Create onboarding guide",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 22,
    title: "Prepare client presentation",
    status: TaskStatus.Completed,
    priority: TaskPriority.Low,
  },
  {
    id: 23,
    title: "Configure analytics tracking",
    status: TaskStatus.InProgress,
    priority: TaskPriority.None,
  },
  {
    id: 24,
    title: "Conduct code review session",
    status: TaskStatus.Completed,
    priority: TaskPriority.High,
  },
  {
    id: 25,
    title: "Fix mobile responsiveness issues",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.None,
  },
  {
    id: 26,
    title: "Improve error handling",
    status: TaskStatus.Completed,
    priority: TaskPriority.None,
  },
  {
    id: 27,
    title: "Set up monitoring alerts",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 28,
    title: "Design new logo",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 29,
    title: "Analyze customer feedback",
    status: TaskStatus.Completed,
    priority: TaskPriority.High,
  },
  {
    id: 30,
    title: "Write blog post on best practices",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.None,
  },
  {
    id: 31,
    title: "Document REST API endpoints",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 32,
    title: "Refactor checkout flow",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Urgent,
  },
  {
    id: 33,
    title: "Optimize image loading",
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
  },
  {
    id: 34,
    title: "Update security policies",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.None,
  },
  {
    id: 35,
    title: "Develop user profile page",
    status: TaskStatus.Completed,
    priority: TaskPriority.Urgent,
  },
  {
    id: 36,
    title: "Fix broken links in footer",
    status: TaskStatus.InProgress,
    priority: TaskPriority.None,
  },
  {
    id: 37,
    title: "Set up automated email responses",
    status: TaskStatus.Completed,
    priority: TaskPriority.None,
  },
  {
    id: 38,
    title: "Improve site accessibility",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 39,
    title: "Create A/B test experiment",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 40,
    title: "Conduct usability testing",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.High,
  },
  {
    id: 41,
    title: "Write post-mortem for outage",
    status: TaskStatus.Completed,
    priority: TaskPriority.None,
  },
  {
    id: 42,
    title: "Fix pagination issues",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.High,
  },
  {
    id: 43,
    title: "Build dashboard charts",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 44,
    title: "Write test cases for search functionality",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Urgent,
  },
  {
    id: 45,
    title: "Improve onboarding flow",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 46,
    title: "Optimize SQL queries",
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
  },
  {
    id: 47,
    title: "Deploy new microservice",
    status: TaskStatus.InProgress,
    priority: TaskPriority.None,
  },
  {
    id: 48,
    title: "Fix UI inconsistencies",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.None,
  },
  {
    id: 49,
    title: "Update payment gateway integration",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 50,
    title: "Investigate slow API response times",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 51,
    title: "Prepare for product launch",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 52,
    title: "Write user documentation",
    status: TaskStatus.Completed,
    priority: TaskPriority.Low,
  },
  {
    id: 53,
    title: "Update README file",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Medium,
  },
  {
    id: 54,
    title: "Fix session expiration bug",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Urgent,
  },
  {
    id: 55,
    title: "Develop chat feature",
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
  },
  {
    id: 56,
    title: "Research AI integration",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Low,
  },
  {
    id: 57,
    title: "Improve website SEO",
    status: TaskStatus.Completed,
    priority: TaskPriority.Urgent,
  },
  {
    id: 58,
    title: "Analyze error logs",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Urgent,
  },
  {
    id: 59,
    title: "Redesign settings page",
    status: TaskStatus.Completed,
    priority: TaskPriority.Low,
  },
  {
    id: 60,
    title: "Enhance form validation",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 61,
    title: "Update email templates",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Low,
  },
  {
    id: 62,
    title: "Set up feature flags",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Low,
  },
  {
    id: 63,
    title: "Fix typos in UI copy",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 64,
    title: "Refactor old legacy code",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.High,
  },
  {
    id: 65,
    title: "Prepare training slides",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 66,
    title: "Create FAQ section",
    status: TaskStatus.Completed,
    priority: TaskPriority.Low,
  },
  {
    id: 67,
    title: "Fix timezone issues",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.None,
  },
  {
    id: 68,
    title: "Add 2FA authentication",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.None,
  },
  {
    id: 69,
    title: "Implement search autocomplete",
    status: TaskStatus.Completed,
    priority: TaskPriority.High,
  },
  {
    id: 70,
    title: "Improve cache strategy",
    status: TaskStatus.Completed,
    priority: TaskPriority.Urgent,
  },
  {
    id: 71,
    title: "Update terms of service",
    status: TaskStatus.Completed,
    priority: TaskPriority.None,
  },
  {
    id: 72,
    title: "Research new frontend framework",
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
  },
  {
    id: 73,
    title: "Enhance error messages",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 74,
    title: "Fix memory leak issue",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Medium,
  },
  {
    id: 75,
    title: "Develop new admin panel",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 76,
    title: "Review customer support tickets",
    status: TaskStatus.Completed,
    priority: TaskPriority.High,
  },
  {
    id: 77,
    title: "Run load tests",
    status: TaskStatus.Completed,
    priority: TaskPriority.Urgent,
  },
  {
    id: 78,
    title: "Write Cypress tests",
    status: TaskStatus.Completed,
    priority: TaskPriority.High,
  },
  {
    id: 79,
    title: "Create interactive tutorial",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 80,
    title: "Fix API CORS issues",
    status: TaskStatus.Completed,
    priority: TaskPriority.None,
  },
  {
    id: 81,
    title: "Enhance keyboard navigation",
    status: TaskStatus.Completed,
    priority: TaskPriority.Urgent,
  },
  {
    id: 82,
    title: "Update user avatars",
    status: TaskStatus.InProgress,
    priority: TaskPriority.None,
  },
  {
    id: 83,
    title: "Test backup recovery",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Urgent,
  },
  {
    id: 84,
    title: "Update mobile app version",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Low,
  },
  {
    id: 85,
    title: "Monitor server logs",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 86,
    title: "Fix infinite scroll bug",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 87,
    title: "Improve site speed",
    status: TaskStatus.InProgress,
    priority: TaskPriority.None,
  },
  {
    id: 88,
    title: "Write migration script",
    status: TaskStatus.Completed,
    priority: TaskPriority.High,
  },
  {
    id: 89,
    title: "Develop feature toggles",
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
  },
  {
    id: 90,
    title: "Refactor modal components",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 91,
    title: "Conduct A11y audit",
    status: TaskStatus.Completed,
    priority: TaskPriority.High,
  },
  {
    id: 92,
    title: "Test WebSocket connections",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Medium,
  },
  {
    id: 93,
    title: "Optimize database indexing",
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
  },
  {
    id: 94,
    title: "Fix missing translations",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Urgent,
  },
  {
    id: 95,
    title: "Investigate 500 errors",
    status: TaskStatus.Completed,
    priority: TaskPriority.None,
  },
  {
    id: 96,
    title: "Update dark mode styling",
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
  },
  {
    id: 97,
    title: "Review legal compliance",
    status: TaskStatus.InProgress,
    priority: TaskPriority.None,
  },
  {
    id: 98,
    title: "Write changelog updates",
    status: TaskStatus.Completed,
    priority: TaskPriority.None,
  },
  {
    id: 99,
    title: "Deploy security patches",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 100,
    title: "Refactor Redux state",
    status: TaskStatus.Completed,
    priority: TaskPriority.High,
  },
  {
    id: 101,
    title: "Fix sidebar navigation",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 102,
    title: "Improve touch gestures",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 103,
    title: "Update typography guidelines",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Low,
  },
  {
    id: 104,
    title: "Test push notifications",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Low,
  },
  {
    id: 105,
    title: "Fix dropdown positioning",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.Low,
  },
  {
    id: 106,
    title: "Develop new analytics dashboard",
    status: TaskStatus.Completed,
    priority: TaskPriority.Urgent,
  },
  {
    id: 107,
    title: "Reduce bundle size",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 108,
    title: "Refactor date parsing functions",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Urgent,
  },
  {
    id: 109,
    title: "Improve modal animations",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Urgent,
  },
  {
    id: 110,
    title: "Run penetration tests",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.High,
  },
  {
    id: 111,
    title: "Implement JWT authentication",
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 112,
    title: "Improve logging strategy",
    status: TaskStatus.InProgress,
    priority: TaskPriority.None,
  },
  {
    id: 113,
    title: "Optimize Redis caching",
    status: TaskStatus.NotStarted,
    priority: TaskPriority.High,
  },
];
